# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import ServiceClient
from msrest import Configuration, Serializer, Deserializer
from .version import VERSION
from msrest.exceptions import HttpOperationError
from .operations.admin_api_client_operations import AdminApiClientOperations
from .operations.admin_application_operations import AdminApplicationOperations
from .operations.admin_dashboard_operations import AdminDashboardOperations
from .operations.admin_ems_system_operations import AdminEmsSystemOperations
from .operations.admin_group_operations import AdminGroupOperations
from .operations.admin_user_operations import AdminUserOperations
from .operations.analytic_operations import AnalyticOperations
from .operations.analytic_set_operations import AnalyticSetOperations
from .operations.asset_operations import AssetOperations
from .operations.database_operations import DatabaseOperations
from .operations.ems_profile_operations import EmsProfileOperations
from .operations.ems_system_operations import EmsSystemOperations
from .operations.html_documentation_operations import HtmlDocumentationOperations
from .operations.navigation_operations import NavigationOperations
from .operations.parameter_set_operations import ParameterSetOperations
from .operations.profile_operations import ProfileOperations
from .operations.tableau_operations import TableauOperations
from .operations.trajectory_operations import TrajectoryOperations
from .operations.transfer_operations import TransferOperations
from .operations.upload_operations import UploadOperations
from .operations.weather_operations import WeatherOperations
from . import models


class EMSAPIv2Configuration(Configuration):
    """Configuration for EMSAPIv2
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        if not base_url:
            base_url = 'https://ems.efoqa.com:443/api'

        super(EMSAPIv2Configuration, self).__init__(base_url)

        self.add_user_agent('emsapiv2/{}'.format(VERSION))


class EMSAPIv2(object):
    """The second version of the REST-based API for accessing EMS data

    :ivar config: Configuration for client.
    :vartype config: EMSAPIv2Configuration

    :ivar admin_api_client: AdminApiClient operations
    :vartype admin_api_client: swagger.operations.AdminApiClientOperations
    :ivar admin_application: AdminApplication operations
    :vartype admin_application: swagger.operations.AdminApplicationOperations
    :ivar admin_dashboard: AdminDashboard operations
    :vartype admin_dashboard: swagger.operations.AdminDashboardOperations
    :ivar admin_ems_system: AdminEmsSystem operations
    :vartype admin_ems_system: swagger.operations.AdminEmsSystemOperations
    :ivar admin_group: AdminGroup operations
    :vartype admin_group: swagger.operations.AdminGroupOperations
    :ivar admin_user: AdminUser operations
    :vartype admin_user: swagger.operations.AdminUserOperations
    :ivar analytic: Analytic operations
    :vartype analytic: swagger.operations.AnalyticOperations
    :ivar analytic_set: AnalyticSet operations
    :vartype analytic_set: swagger.operations.AnalyticSetOperations
    :ivar asset: Asset operations
    :vartype asset: swagger.operations.AssetOperations
    :ivar database: Database operations
    :vartype database: swagger.operations.DatabaseOperations
    :ivar ems_profile: EmsProfile operations
    :vartype ems_profile: swagger.operations.EmsProfileOperations
    :ivar ems_system: EmsSystem operations
    :vartype ems_system: swagger.operations.EmsSystemOperations
    :ivar html_documentation: HtmlDocumentation operations
    :vartype html_documentation: swagger.operations.HtmlDocumentationOperations
    :ivar navigation: Navigation operations
    :vartype navigation: swagger.operations.NavigationOperations
    :ivar parameter_set: ParameterSet operations
    :vartype parameter_set: swagger.operations.ParameterSetOperations
    :ivar profile: Profile operations
    :vartype profile: swagger.operations.ProfileOperations
    :ivar tableau: Tableau operations
    :vartype tableau: swagger.operations.TableauOperations
    :ivar trajectory: Trajectory operations
    :vartype trajectory: swagger.operations.TrajectoryOperations
    :ivar transfer: Transfer operations
    :vartype transfer: swagger.operations.TransferOperations
    :ivar upload: Upload operations
    :vartype upload: swagger.operations.UploadOperations
    :ivar weather: Weather operations
    :vartype weather: swagger.operations.WeatherOperations

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        self.config = EMSAPIv2Configuration(base_url)
        self._client = ServiceClient(None, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = 'v2'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.admin_api_client = AdminApiClientOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.admin_application = AdminApplicationOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.admin_dashboard = AdminDashboardOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.admin_ems_system = AdminEmsSystemOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.admin_group = AdminGroupOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.admin_user = AdminUserOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.analytic = AnalyticOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.analytic_set = AnalyticSetOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.asset = AssetOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.database = DatabaseOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.ems_profile = EmsProfileOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.ems_system = EmsSystemOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.html_documentation = HtmlDocumentationOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.navigation = NavigationOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.parameter_set = ParameterSetOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.profile = ProfileOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.tableau = TableauOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.trajectory = TrajectoryOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.transfer = TransferOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.upload = UploadOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.weather = WeatherOperations(
            self._client, self.config, self._serialize, self._deserialize)
