# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoAnalyticInfo(Model):
    """Encapsulates information about an analytic.

    :param id: The identifier for the analytic
    :type id: str
    :param name: The name of the analytic
    :type name: str
    :param description: The description of the analytic
    :type description: str
    :param units: The units of the analytic
    :type units: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'units': {'key': 'units', 'type': 'str'},
    }

    def __init__(self, id=None, name=None, description=None, units=None):
        super(AdiEmsWebApiV2DtoAnalyticInfo, self).__init__()
        self.id = id
        self.name = name
        self.description = description
        self.units = units
