# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2ModelAdminDashboardsImport(Model):
    """Represents a message used to provide information to users about an action
    that took place in an API request.

    :param imports: The list of imported dashboards and information gathered
     for each performed import.
    :type imports:
     list[~swagger.models.AdiEmsWebApiV2ModelAdminDashboardImport]
    :param summary: A summary messaged intended to be shown to users of what
     happened in the import process.
    :type summary: ~swagger.models.AdiEmsWebApiV2ModelApiMessage
    """

    _attribute_map = {
        'imports': {'key': 'imports', 'type': '[AdiEmsWebApiV2ModelAdminDashboardImport]'},
        'summary': {'key': 'summary', 'type': 'AdiEmsWebApiV2ModelApiMessage'},
    }

    def __init__(self, imports=None, summary=None):
        super(AdiEmsWebApiV2ModelAdminDashboardsImport, self).__init__()
        self.imports = imports
        self.summary = summary
