# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoSchemaUpdateColumn(Model):
    """Represents a column to be updated.

    :param field_id: The unique string identifier of the field to update.
    :type field_id: str
    :param value: The new value for the field.
    :type value: object
    """

    _validation = {
        'field_id': {'required': True},
        'value': {'required': True},
    }

    _attribute_map = {
        'field_id': {'key': 'fieldId', 'type': 'str'},
        'value': {'key': 'value', 'type': 'object'},
    }

    def __init__(self, field_id, value):
        super(AdiEmsWebApiV2DtoSchemaUpdateColumn, self).__init__()
        self.field_id = field_id
        self.value = value
