# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoSchemaUpdate(Model):
    """Represents the options used to make up an update.

    :param update_columns: An array specifying the fields to update (and their
     values).
    :type update_columns:
     list[~swagger.models.AdiEmsWebApiV2DtoSchemaUpdateColumn]
    :param filter: A filter used to narrow the update results.
    :type filter: ~swagger.models.AdiEmsWebApiV2DtoSchemaFilter
    """

    _validation = {
        'update_columns': {'required': True},
    }

    _attribute_map = {
        'update_columns': {'key': 'updateColumns', 'type': '[AdiEmsWebApiV2DtoSchemaUpdateColumn]'},
        'filter': {'key': 'filter', 'type': 'AdiEmsWebApiV2DtoSchemaFilter'},
    }

    def __init__(self, update_columns, filter=None):
        super(AdiEmsWebApiV2DtoSchemaUpdate, self).__init__()
        self.update_columns = update_columns
        self.filter = filter
