# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .emsap_iv2 import EMSAPIv2
from .version import VERSION

__all__ = ['EMSAPIv2']

__version__ = VERSION

