# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2ModelTableauTableauServer(Model):
    """Represents information about the associated Tableau server.

    :param url: The root URL of the Tableau server with site.
    :type url: str
    :param site: The site being used.
    :type site: str
    """

    _attribute_map = {
        'url': {'key': 'url', 'type': 'str'},
        'site': {'key': 'site', 'type': 'str'},
    }

    def __init__(self, url=None, site=None):
        super(AdiEmsWebApiV2ModelTableauTableauServer, self).__init__()
        self.url = url
        self.site = site
