# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2ModelAnalyticOffsetType(Model):
    """Class for determining which offsets to sample an analytic at.

    :param type: Determines the way to retrieve samples for an analytic query.
     Possible values include: 'sampledValues', 'fixedRate'
    :type type: str or ~emsapi.models.enum
    :param sampling_rate: Offsets are calculated using this sampling rate when
     using 'FixedRate' sampling type.
    :type sampling_rate: float
    """

    _validation = {
        'type': {'required': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'sampling_rate': {'key': 'samplingRate', 'type': 'float'},
    }

    def __init__(self, type, sampling_rate=None):
        super(AdiEmsWebApiV2ModelAnalyticOffsetType, self).__init__()
        self.type = type
        self.sampling_rate = sampling_rate
