# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoWeatherTafTurbulenceCondition(Model):
    """Describes a forecast turbulence condition.

    :param intensity: The intensity code associated with the turbulence. Uses
     the following values:
     0 - None,
     1 - Light turbulence,
     2 - Moderate turbulence in clear air (occasional),
     3 - Moderate turbulence in clear air (frequent),
     4 - Moderate turbulence in cloud (occasional),
     5 - Moderate turbulence in cloud (frequent),
     6 - Severe turbulence in clear air (occasional),
     7 - Severe turbulence in clear air (frequent),
     8 - Severe turbulence in cloud (occasional),
     9 - Severe turbulence in cloud (frequent)
    :type intensity: int
    :param minimum: The base limit of the turbulence layer in feet
    :type minimum: int
    :param maximum: The top limit of the turbulence layer in feet
    :type maximum: int
    """

    _attribute_map = {
        'intensity': {'key': 'intensity', 'type': 'int'},
        'minimum': {'key': 'minimum', 'type': 'int'},
        'maximum': {'key': 'maximum', 'type': 'int'},
    }

    def __init__(self, intensity=None, minimum=None, maximum=None):
        super(AdiEmsWebApiV2DtoWeatherTafTurbulenceCondition, self).__init__()
        self.intensity = intensity
        self.minimum = minimum
        self.maximum = maximum
