# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebSharedTableauRestProject(Model):
    """AdiEmsWebSharedTableauRestProject.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param description:
    :type description: str
    :param content_permissions:
    :type content_permissions: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'content_permissions': {'key': 'contentPermissions', 'type': 'str'},
    }

    def __init__(self, id=None, name=None, description=None, content_permissions=None):
        super(AdiEmsWebSharedTableauRestProject, self).__init__()
        self.id = id
        self.name = name
        self.description = description
        self.content_permissions = content_permissions
