# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoSchemaDatabaseGroup(Model):
    """Represents a folder in the database tree of an EMS installation.

    :param id: The unique string identifier for the database group
    :type id: str
    :param name: The display name for the database group
    :type name: str
    :param groups: An ordered listing of child database groups contained in
     this group
    :type groups: list[~emsapi.models.AdiEmsWebApiV2DtoSchemaDatabaseGroup]
    :param databases: An ordered listing of child databases contained in this
     group
    :type databases: list[~emsapi.models.AdiEmsWebApiV2DtoSchemaDatabase]
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'groups': {'key': 'groups', 'type': '[AdiEmsWebApiV2DtoSchemaDatabaseGroup]'},
        'databases': {'key': 'databases', 'type': '[AdiEmsWebApiV2DtoSchemaDatabase]'},
    }

    def __init__(self, id, name, groups=None, databases=None):
        super(AdiEmsWebApiV2DtoSchemaDatabaseGroup, self).__init__()
        self.id = id
        self.name = name
        self.groups = groups
        self.databases = databases
