# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoParameterSetParameterSetGroup(Model):
    """A container for parameter sets.

    :param name: The name of the group.
    :type name: str
    :param group_id: The id of the group. This should be a relative path.
    :type group_id: str
    :param groups: An array of groups contained by this group.
    :type groups:
     list[~emsapi.models.AdiEmsWebApiV2DtoParameterSetParameterSetGroup]
    :param sets: An array of parameter sets contained by this group.
    :type sets: list[~emsapi.models.AdiEmsWebApiV2DtoParameterSetParameterSet]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'group_id': {'key': 'groupId', 'type': 'str'},
        'groups': {'key': 'groups', 'type': '[AdiEmsWebApiV2DtoParameterSetParameterSetGroup]'},
        'sets': {'key': 'sets', 'type': '[AdiEmsWebApiV2DtoParameterSetParameterSet]'},
    }

    def __init__(self, name=None, group_id=None, groups=None, sets=None):
        super(AdiEmsWebApiV2DtoParameterSetParameterSetGroup, self).__init__()
        self.name = name
        self.group_id = group_id
        self.groups = groups
        self.sets = sets
