# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoEmsProfileGlossaryItem(Model):
    """Represents a single entry for an item in a profile glossary.

    :param record_type: A character representing a profile glossary entries
     record type.
    :type record_type: str
    :param scope: A character representing the scope of this entry.
    :type scope: str
    :param item_id: A unique integer id for this item.
    :type item_id: int
    :param event_type_id: The event type id of this item. This is only
     available for valid event types.
    :type event_type_id: int
    :param data_type: A character representing the data type of this entry.
    :type data_type: str
    :param logical_id: A GUID defining this item's logical id.
    :type logical_id: str
    :param name: The name provided for this item.
    :type name: str
    :param units: An optional unit provided for this item.
    :type units: str
    :param first_associated_item_type: The item type of the first associated
     item.
    :type first_associated_item_type: str
    :param first_associated_item_scope: The scope of the first associated
     item.
    :type first_associated_item_scope: str
    :param first_associated_item_id: The item id of the first associated item.
    :type first_associated_item_id: int
    :param second_associated_item_type: The item type of the second associated
     item.
    :type second_associated_item_type: str
    :param second_associated_item_scope: The scope of the second associated
     item.
    :type second_associated_item_scope: str
    :param second_associated_item_id: The item id of the second associated
     item.
    :type second_associated_item_id: int
    """

    _attribute_map = {
        'record_type': {'key': 'recordType', 'type': 'str'},
        'scope': {'key': 'scope', 'type': 'str'},
        'item_id': {'key': 'itemId', 'type': 'int'},
        'event_type_id': {'key': 'eventTypeId', 'type': 'int'},
        'data_type': {'key': 'dataType', 'type': 'str'},
        'logical_id': {'key': 'logicalId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'units': {'key': 'units', 'type': 'str'},
        'first_associated_item_type': {'key': 'firstAssociatedItemType', 'type': 'str'},
        'first_associated_item_scope': {'key': 'firstAssociatedItemScope', 'type': 'str'},
        'first_associated_item_id': {'key': 'firstAssociatedItemId', 'type': 'int'},
        'second_associated_item_type': {'key': 'secondAssociatedItemType', 'type': 'str'},
        'second_associated_item_scope': {'key': 'secondAssociatedItemScope', 'type': 'str'},
        'second_associated_item_id': {'key': 'secondAssociatedItemId', 'type': 'int'},
    }

    def __init__(self, record_type=None, scope=None, item_id=None, event_type_id=None, data_type=None, logical_id=None, name=None, units=None, first_associated_item_type=None, first_associated_item_scope=None, first_associated_item_id=None, second_associated_item_type=None, second_associated_item_scope=None, second_associated_item_id=None):
        super(AdiEmsWebApiV2DtoEmsProfileGlossaryItem, self).__init__()
        self.record_type = record_type
        self.scope = scope
        self.item_id = item_id
        self.event_type_id = event_type_id
        self.data_type = data_type
        self.logical_id = logical_id
        self.name = name
        self.units = units
        self.first_associated_item_type = first_associated_item_type
        self.first_associated_item_scope = first_associated_item_scope
        self.first_associated_item_id = first_associated_item_id
        self.second_associated_item_type = second_associated_item_type
        self.second_associated_item_scope = second_associated_item_scope
        self.second_associated_item_id = second_associated_item_id
