# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoSchemaField(Model):
    """Represents an individual field that can be accessed within a data source.

    :param id: The unique string identifier for the field
    :type id: str
    :param type: The data type of the underlying data stored for the field.
     Possible values include: 'boolean', 'dateTime', 'discrete', 'number',
     'string'
    :type type: str or ~emsapi.models.enum
    :param name: The display name for the field
    :type name: str
    """

    _validation = {
        'id': {'required': True},
        'type': {'required': True},
        'name': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, id, type, name):
        super(AdiEmsWebApiV2DtoSchemaField, self).__init__()
        self.id = id
        self.type = type
        self.name = name
