# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoProfileProfile(Model):
    """Represents an APM (Automated Parameter Measurement) profile in an EMS
    system.

    :param local_id: The local integer identifier for the profile
    :type local_id: int
    :param id: The globally unique identifier of the profile
    :type id: str
    :param name: The display name of the profile
    :type name: str
    :param library: Indicates whether the profile is a "library" profile
    :type library: bool
    :param current_version: The current integer version of the profile
    :type current_version: int
    """

    _validation = {
        'local_id': {'required': True},
        'id': {'required': True},
        'name': {'required': True},
        'library': {'required': True},
        'current_version': {'required': True},
    }

    _attribute_map = {
        'local_id': {'key': 'localId', 'type': 'int'},
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'library': {'key': 'library', 'type': 'bool'},
        'current_version': {'key': 'currentVersion', 'type': 'int'},
    }

    def __init__(self, local_id, id, name, library, current_version):
        super(AdiEmsWebApiV2DtoProfileProfile, self).__init__()
        self.local_id = local_id
        self.id = id
        self.name = name
        self.library = library
        self.current_version = current_version
