# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2ModelAdminDashboardIds(Model):
    """Represents a structure for specifying one or existing dashboard IDs.

    :param ids: An array specifying one or more unique IDs of existing
     dashboards.
    :type ids: list[int]
    """

    _validation = {
        'ids': {'required': True},
    }

    _attribute_map = {
        'ids': {'key': 'ids', 'type': '[int]'},
    }

    def __init__(self, ids):
        super(AdiEmsWebApiV2ModelAdminDashboardIds, self).__init__()
        self.ids = ids
