# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiModelError(Model):
    """AdiEmsWebApiModelError.

    :param message:
    :type message: str
    :param message_detail:
    :type message_detail: str
    :param unexpected:
    :type unexpected: bool
    """

    _validation = {
        'message': {'required': True},
        'message_detail': {'required': True},
        'unexpected': {'required': True},
    }

    _attribute_map = {
        'message': {'key': 'message', 'type': 'str'},
        'message_detail': {'key': 'messageDetail', 'type': 'str'},
        'unexpected': {'key': 'unexpected', 'type': 'bool'},
    }

    def __init__(self, message, message_detail, unexpected):
        super(AdiEmsWebApiModelError, self).__init__()
        self.message = message
        self.message_detail = message_detail
        self.unexpected = unexpected
